@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.trinkets.renderer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;