import groovy.json.JsonOutput
import groovy.json.JsonSlurper

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

wrapper {
	gradleVersion = '9.5.1'
	distributionType = Wrapper.DistributionType.ALL
}

def secrets = new Properties()
def secretsFile = file('secrets.properties')
if (secretsFile.exists()) {
	secretsFile.withInputStream { stream -> secrets.load(stream) }

	fileTree("secrets").matching {
		include "**/*.properties"
	}.each { File file ->
		file.withInputStream { stream -> secrets.load(stream) }
	}
}

version = (hasProperty("CIRevision") ? CIRevision : project.mod_version)
group = group_name

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs << "-Xlint:all,-classfile,-processing,-deprecation,-this-escape" << "-Werror"
	options.encoding = 'UTF-8'
	it.options.release = 25
}

base {
	archivesName = "${project.mod_id}-${project.minecraft_version}"
}

subprojects {
	version = project(":").version
}

fabricApi {
	configureDataGeneration {
		modId = "twilightforest"
		outputDirectory = file("src/generated/resources")
		client = true
	}
}

loom {
	accessWidenerPath = file("src/main/resources/twilightforest.classtweaker")
	enableTransitiveAccessWideners = true

	interfaceInjection {
		enableDependencyInterfaceInjection = true
	}

	runs {
		client {
			client()
			configName = "Fabric Client"
			runDir = "run"
			programArgs "--username", (secrets.getProperty("username") ?: "Dev")
		}

		server {
			server()
			configName = "Fabric Server"
			runDir = "run"
		}
	}
}

sourceSets {
	main {
		resources {
			srcDir 'src/generated/resources'
			exclude '.cache'
		}
	}

	data {
		compileClasspath += main.compileClasspath + main.output

		java {
			srcDirs = ['src/main/java', 'src/data/java']
		}
		resources {
			srcDirs = ['src/main/resources']
		}
	}
}

configurations {
	dataImplementation.extendsFrom implementation
}

repositories {
	mavenLocal()
	maven {
		name = "Fuzs Mod Resources" // Forge Config API Port
		url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
	}
}

dependencies {
	// Minecraft & Fabric
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

	// Built in library
	implementation project(":carminite")

	// NeoForge Compatibility
	include(implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api_port_version}")
}

processResources {
	def ver = project.version
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	inputs.property "version", ver

	filesMatching("fabric.mod.json") {
		expand([
			"version"             : ver,
			"loader_version"      : loader_version,
			"minecraft_version"   : minecraft_version,
			"fabric_api_version"  : fabric_api_version,
			"java_version"        : java.toolchain.languageVersion.get().asInt()
		])
	}

	exclude ".cache"

	def lazyTree = providers.provider {
		fileTree(dir: getOutputs().getFiles().getAsPath(), includes: ["**/*.json", "**/*.mcmeta"])
	}

	doLast {
		lazyTree.get().each { File file ->
			file.setText(JsonOutput.toJson(new JsonSlurper().parse(file)))
		}
	}
}

jar {
	exclude 'data/twilightforest/function/**'

	manifest {
		attributes([
			'Specification-Title'     : mod_id,
			'Specification-Vendor'    : "TeamTwilight",
			'Specification-Version'   : "1",
			'Implementation-Title'    : project.name,
			'Implementation-Version'  : project.version,
			'Implementation-Vendor'   : "TeamTwilight",
			'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

tasks.register('sourceJar', Jar) {
	dependsOn 'classes'
	from sourceSets.main.allSource
	archiveClassifier = 'sources'
}

tasks.register('dataJar', Jar) {
	dependsOn 'classes'
	from sourceSets.data.output
	archiveClassifier = 'data'
}

tasks.register('dataSourceJar', Jar) {
	from sourceSets.data.allSource
	archiveClassifier = 'data-sources'
}

def mavenUser = System.getenv("MAVEN_USER") ?: secrets.getProperty("maven_username")
def mavenToken = System.getenv("MAVEN_PASS") ?: secrets.getProperty("maven_password")

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifact jar
			artifact sourceJar
			artifact dataJar
			artifact dataSourceJar

			groupId = 'team-twilight'
			artifactId = project.mod_id

			pom {
				withXml {
					def dependenciesNode = asNode().appendNode('dependencies')

					def addDep = { String group, String name, String version ->
						def depNode = dependenciesNode.appendNode('dependency')
						depNode.appendNode('groupId', group)
						depNode.appendNode('artifactId', name)
						depNode.appendNode('version', version)
						depNode.appendNode('scope', 'compile')
					}

					addDep('tamaized', 'beanification', project.beanification_version)
				}
			}
		}
	}

	repositories {
		maven {
			url "https://maven.tamaized.com/releases"
			credentials {
				username mavenUser
				password mavenToken
			}
		}
	}
}