org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.configuration-cache=false

# Mod Info
mod_version=4.8
mod_id=twilightforest-fabric
group_name=com.github.teamtwilight.twilightforest

# Minecraft
base_minecraft_version=1.21
minecraft_version=1.21.1

# Fabric
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.116.15+1.21.1

# Parchment Mappings
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

# Deps
jei_version=19.43.0.392
rei_version=16.0.799
emi_version=1.1.24
trinkets_version=3.10.0
jade_version=15.10.5+fabric
modmenu_version=11.0.4
porting_lib_version=3.1.0-beta.89

enable_tips_mod=false