org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Mod Info
mod_version=4.8
mod_id=twilightforest
group_name=com.github.teamtwilight.twilightforest

# Minecraft
base_minecraft_version=26.1
minecraft_version=26.1.2

# Fabric: https://fabricmc.net/develop/
loom_version=1.17-SNAPSHOT
loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2

# Deps
forge_config_api_port_version=26.1.5
