@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.curios.model;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;