@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.curios;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;