@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.trinkets.model;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;