@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.trinkets;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;