accessWidener	v1	named
accessible field net/minecraft/world/entity/Entity yRot F
accessible field net/minecraft/world/entity/Entity xRot F
accessible method net/minecraft/world/damagesource/DamageSource bypassArmor ()Lnet/minecraft/world/damagesource/DamageSource;
accessible method net/minecraft/world/damagesource/DamageSource <init> (Ljava/lang/String;)V
accessible field net/minecraft/world/entity/animal/Parrot MOB_SOUND_MAP Ljava/util/Map;
mutable field net/minecraft/world/level/saveddata/maps/MapItemSavedData x I
mutable field net/minecraft/world/level/saveddata/maps/MapItemSavedData z I
accessible method net/minecraft/world/level/saveddata/maps/MapItemSavedData <init> (IIBZZZLnet/minecraft/resources/ResourceKey;)V
accessible method net/minecraft/world/level/block/state/properties/WoodType register (Lnet/minecraft/world/level/block/state/properties/WoodType;)Lnet/minecraft/world/level/block/state/properties/WoodType;
accessible method net/minecraft/world/level/block/state/properties/WoodType <init> (Ljava/lang/String;)V
accessible method net/minecraft/client/renderer/item/ItemProperties register (Lnet/minecraft/world/item/Item;Lnet/minecraft/resources/ResourceLocation;Lnet/minecraft/client/renderer/item/ClampedItemPropertyFunction;)V
accessible field net/minecraft/world/item/AxeItem STRIPPABLES Ljava/util/Map;
accessible field net/minecraft/world/level/chunk/ChunkBiomeContainer biomes [Lnet/minecraft/world/level/biome/Biome;
accessible method net/minecraft/core/particles/SimpleParticleType <init> (Z)V
accessible method net/minecraft/client/particle/ParticleEngine register (Lnet/minecraft/core/particles/ParticleType;Lnet/minecraft/client/particle/ParticleEngine$SpriteParticleRegistration;)V
accessible class net/minecraft/world/level/block/entity/BlockEntityType$BlockEntitySupplier
accessible method net/minecraft/world/level/block/entity/BlockEntityType$BlockEntitySupplier create (Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)Lnet/minecraft/world/level/block/entity/BlockEntity;
accessible field net/minecraft/world/level/saveddata/maps/MapItemSavedData decorations Ljava/util/Map;
accessible field net/minecraft/world/entity/player/Player abilities Lnet/minecraft/world/entity/player/Abilities;
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity litTime I
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity litDuration I
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity cookingProgress I
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity cookingTotalTime I
accessible method net/minecraft/client/renderer/blockentity/BlockEntityRenderers register (Lnet/minecraft/world/level/block/entity/BlockEntityType;Lnet/minecraft/client/renderer/blockentity/BlockEntityRendererProvider;)V
accessible field net/minecraft/world/level/newbiome/layer/Layer area Lnet/minecraft/world/level/newbiome/area/LazyArea;
accessible method net/minecraft/world/inventory/MenuType <init> (Lnet/minecraft/world/inventory/MenuType$MenuSupplier;)V
mutable field net/minecraft/world/item/AxeItem STRIPPABLES Ljava/util/Map;
accessible field net/minecraft/client/renderer/DimensionSpecialEffects EFFECTS Lit/unimi/dsi/fastutil/objects/Object2ObjectMap;
accessible field net/minecraft/world/entity/Entity portalTime I
accessible method net/minecraft/world/level/block/WoodButtonBlock <init> (Lnet/minecraft/world/level/block/state/BlockBehaviour$Properties;)V
accessible method net/minecraft/world/level/block/PressurePlateBlock <init> (Lnet/minecraft/world/level/block/PressurePlateBlock$Sensitivity;Lnet/minecraft/world/level/block/state/BlockBehaviour$Properties;)V
accessible method net/minecraft/world/level/block/DoorBlock <init> (Lnet/minecraft/world/level/block/state/BlockBehaviour$Properties;)V
accessible method net/minecraft/world/level/block/TrapDoorBlock <init> (Lnet/minecraft/world/level/block/state/BlockBehaviour$Properties;)V
accessible method net/minecraft/world/level/block/StairBlock <init> (Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/block/state/BlockBehaviour$Properties;)V
accessible method net/minecraft/world/level/block/HalfTransparentBlock <init> (Lnet/minecraft/world/level/block/state/BlockBehaviour$Properties;)V
accessible method net/minecraft/world/level/block/SaplingBlock <init> (Lnet/minecraft/world/level/block/grower/AbstractTreeGrower;Lnet/minecraft/world/level/block/state/BlockBehaviour$Properties;)V
accessible class net/minecraft/client/particle/ParticleEngine$SpriteParticleRegistration
accessible method net/minecraft/client/particle/SuspendedTownParticle <init> (Lnet/minecraft/client/multiplayer/ClientLevel;DDDDDD)V
accessible method net/minecraft/client/particle/ParticleEngine register (Lnet/minecraft/core/particles/ParticleType;Lnet/minecraft/client/particle/ParticleProvider;)V
accessible field net/minecraft/world/entity/Entity dimensions Lnet/minecraft/world/entity/EntityDimensions;
accessible field net/minecraft/client/gui/screens/Screen renderables Ljava/util/List;
accessible class net/minecraft/client/Minecraft$ExperimentalDialogType
accessible method net/minecraft/client/renderer/Sheets createSignMaterial (Lnet/minecraft/world/level/block/state/properties/WoodType;)Lnet/minecraft/client/resources/model/Material;
accessible field net/minecraft/server/packs/repository/PackRepository sources Ljava/util/Set;
accessible method net/minecraft/client/renderer/entity/ItemRenderer renderQuadList (Lcom/mojang/blaze3d/vertex/PoseStack;Lcom/mojang/blaze3d/vertex/VertexConsumer;Ljava/util/List;Lnet/minecraft/world/item/ItemStack;II)V
mutable field net/minecraft/world/level/levelgen/StructureSettings DEFAULTS Lcom/google/common/collect/ImmutableMap;
accessible field net/minecraft/world/level/levelgen/flat/FlatLevelGeneratorSettings STRUCTURE_FEATURES Ljava/util/Map;
accessible field net/minecraft/world/level/levelgen/StructureSettings structureConfig Ljava/util/Map;
mutable field net/minecraft/world/level/levelgen/StructureSettings structureConfig Ljava/util/Map;
accessible method net/minecraft/world/inventory/MenuType$MenuSupplier create (ILnet/minecraft/world/entity/player/Inventory;)Lnet/minecraft/world/inventory/AbstractContainerMenu;
accessible method net/minecraft/world/damagesource/DamageSource setIsFire ()Lnet/minecraft/world/damagesource/DamageSource;
accessible field net/minecraft/world/entity/item/FallingBlockEntity fallDamagePerDistance F
accessible field net/minecraft/world/entity/item/FallingBlockEntity fallDamageMax I
accessible field net/minecraft/world/entity/item/FallingBlockEntity hurtEntities Z
accessible field net/minecraft/world/level/saveddata/maps/MapItemSavedData bannerMarkers Ljava/util/Map;
accessible field net/minecraft/world/level/saveddata/maps/MapItemSavedData frameMarkers Ljava/util/Map;
accessible field net/minecraft/world/level/saveddata/maps/MapItemSavedData trackedDecorationCount I
accessible method net/minecraft/server/level/ChunkMap isExistingChunkFull (Lnet/minecraft/world/level/ChunkPos;)Z
accessible field net/minecraft/client/renderer/LevelRenderer skyBuffer Lcom/mojang/blaze3d/vertex/VertexBuffer;
accessible field net/minecraft/client/renderer/LevelRenderer darkBuffer Lcom/mojang/blaze3d/vertex/VertexBuffer;
mutable field net/minecraft/world/entity/player/Inventory player Lnet/minecraft/world/entity/player/Player;
accessible field net/minecraft/client/model/geom/LayerDefinitions FISH_PATTERN_DEFORMATION Lnet/minecraft/client/model/geom/builders/CubeDeformation;
accessible field net/minecraft/client/model/geom/LayerDefinitions OUTER_ARMOR_DEFORMATION Lnet/minecraft/client/model/geom/builders/CubeDeformation;
accessible field net/minecraft/client/model/geom/LayerDefinitions INNER_ARMOR_DEFORMATION Lnet/minecraft/client/model/geom/builders/CubeDeformation;
accessible class net/minecraft/world/level/levelgen/structure/StructurePiece$BlockSelector
accessible method net/minecraft/world/entity/SpawnPlacements register (Lnet/minecraft/world/entity/EntityType;Lnet/minecraft/world/entity/SpawnPlacements$Type;Lnet/minecraft/world/level/levelgen/Heightmap$Types;Lnet/minecraft/world/entity/SpawnPlacements$SpawnPredicate;)V