accessWidener	v1	named
accessible field net/minecraft/world/entity/Entity yRot F
accessible field net/minecraft/world/entity/Entity xRot F
accessible method net/minecraft/world/damagesource/DamageSource bypassArmor ()Lnet/minecraft/world/damagesource/DamageSource;
accessible method net/minecraft/world/damagesource/DamageSource <init> (Ljava/lang/String;)V
accessible field net/minecraft/world/entity/animal/Parrot MOB_SOUND_MAP Ljava/util/Map;
mutable field net/minecraft/world/level/saveddata/maps/MapItemSavedData x I
mutable field net/minecraft/world/level/saveddata/maps/MapItemSavedData z I
accessible method net/minecraft/world/level/saveddata/maps/MapItemSavedData <init> (IIBZZZLnet/minecraft/resources/ResourceKey;)V
accessible method net/minecraft/world/level/block/state/properties/WoodType register (Lnet/minecraft/world/level/block/state/properties/WoodType;)Lnet/minecraft/world/level/block/state/properties/WoodType;
accessible method net/minecraft/world/level/block/state/properties/WoodType <init> (Ljava/lang/String;)V
accessible method net/minecraft/client/renderer/item/ItemProperties register (Lnet/minecraft/world/item/Item;Lnet/minecraft/resources/ResourceLocation;Lnet/minecraft/client/renderer/item/ClampedItemPropertyFunction;)V
accessible field net/minecraft/world/item/AxeItem STRIPPABLES Ljava/util/Map;
accessible field net/minecraft/world/level/chunk/ChunkBiomeContainer biomes [Lnet/minecraft/world/level/biome/Biome;
accessible method net/minecraft/core/particles/SimpleParticleType <init> (Z)V
accessible method net/minecraft/client/particle/ParticleEngine register (Lnet/minecraft/core/particles/ParticleType;Lnet/minecraft/client/particle/ParticleEngine$SpriteParticleRegistration;)V
accessible class net/minecraft/world/level/block/entity/BlockEntityType$BlockEntitySupplier
accessible method net/minecraft/world/level/block/entity/BlockEntityType$BlockEntitySupplier create (Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)Lnet/minecraft/world/level/block/entity/BlockEntity;
accessible field net/minecraft/world/level/saveddata/maps/MapItemSavedData decorations Ljava/util/Map;
accessible field net/minecraft/world/entity/player/Player abilities Lnet/minecraft/world/entity/player/Abilities;
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity litTime I
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity litDuration I
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity cookingProgress I
accessible field net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity cookingTotalTime I
accessible method net/minecraft/client/renderer/blockentity/BlockEntityRenderers register (Lnet/minecraft/world/level/block/entity/BlockEntityType;Lnet/minecraft/client/renderer/blockentity/BlockEntityRendererProvider;)V
accessible field net/minecraft/world/level/newbiome/layer/Layer area Lnet/minecraft/world/level/newbiome/area/LazyArea;
accessible method net/minecraft/world/inventory/MenuType <init> (Lnet/minecraft/world/inventory/MenuType$MenuSupplier;)V
mutable field net/minecraft/world/item/AxeItem STRIPPABLES Ljava/util/Map;
accessible field net/minecraft/client/renderer/DimensionSpecialEffects EFFECTS Lit/unimi/dsi/fastutil/objects/Object2ObjectMap;
accessible field net/minecraft/world/entity/Entity portalTime I