// Date: 5/18/2012 11:45:03 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package twilightforest.client.model.entity;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.util.LightCoordsUtil;
import net.minecraft.util.Mth;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.ItemDisplayContext;
import twilightforest.client.renderer.entity.AlphaYetiRenderer;
import twilightforest.client.renderer.entity.QuestRamRenderer;
import twilightforest.client.state.entity.QuestingRamRenderState;

import java.util.Arrays;

public class QuestRamModel extends EntityModel<QuestingRamRenderState> implements TrophyBlockModel {

	private final ModelPart head;
	private ModelPart neck;
	private ModelPart frontTorso;
	private ModelPart backTorso;
	private ModelPart leftFrontLeg;
	private ModelPart rightFrontLeg;
	private ModelPart leftBackLeg;
	private ModelPart rightBackLeg;
	private final ModelPart[] segments = new ModelPart[16];

	final int[] colorOrder = new int[]{0, 8, 7, 15, 14, 1, 4, 5, 13, 3, 9, 11, 10, 2, 6, 12};

	public QuestRamModel(ModelPart root) {
		super(root);
		this.head = root.getChild("head");
		if (root.hasChild("neck")) {
			this.neck = root.getChild("neck");
			this.frontTorso = root.getChild("front_torso");
			this.backTorso = root.getChild("back_torso");
			this.leftFrontLeg = root.getChild("left_front_leg");
			this.rightFrontLeg = root.getChild("right_front_leg");
			this.leftBackLeg = root.getChild("left_back_leg");
			this.rightBackLeg = root.getChild("right_back_leg");
			Arrays.setAll(this.segments, (num) -> root.getChild(getSegmentName(num)));
			for (int i = 0; i < 16; i++) {
				this.segments[i].visible = false;
			}
		}
	}

	public static LayerDefinition create() {
		MeshDefinition meshdefinition = new MeshDefinition();
		PartDefinition partdefinition = meshdefinition.getRoot();

		PartDefinition head = partdefinition.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 70).addBox(-6.0F, -5.0F, -11.0F, 12.0F, 9.0F, 15.0F), PartPose.offset(0.0F, -12.0F, -11.0F));

		head.addOrReplaceChild("sloped_head", CubeListBuilder.create()
				.texOffs(54, 73)
				.addBox(-10.0F, -8.5F, -0.5F, 11.0F, 9.0F, 12.0F),
			PartPose.offsetAndRotation(4.5F, 2.0F, -6.0F, 0.5236F, 0.0F, 0.0F));

		head.addOrReplaceChild("left_horn", CubeListBuilder.create()
				.texOffs(0, 94)
				.addBox(5.0F, -45.0F, -14.0F, 4.0F, 4.0F, 6.0F)
				.texOffs(20, 96)
				.addBox(8.0F, -44.0F, -9.0F, 3.0F, 4.0F, 4.0F)
				.texOffs(34, 95)
				.addBox(9.0F, -42.0F, -7.0F, 3.0F, 6.0F, 3.0F)
				.texOffs(46, 98)
				.addBox(10.5F, -38.0F, -9.0F, 3.0F, 3.0F, 3.0F)
				.texOffs(58, 95)
				.addBox(12.0F, -36.0F, -14.0F, 3.0F, 3.0F, 6.0F)
				.texOffs(76, 95)
				.addBox(13.0F, -40.0F, -16.0F, 3.0F, 6.0F, 3.0F)
				.texOffs(88, 97)
				.addBox(14.0F, -42.0F, -14.0F, 3.0F, 3.0F, 4.0F),
			PartPose.offset(0.0F, 36.0F, 11.0F));

		head.addOrReplaceChild("right_horn", CubeListBuilder.create().mirror()
				.texOffs(0, 94)
				.addBox(-9.0F, -45.0F, -14.0F, 4.0F, 4.0F, 6.0F)
				.texOffs(20, 96)
				.addBox(-11.0F, -44.0F, -9.0F, 3.0F, 4.0F, 4.0F)
				.texOffs(34, 95)
				.addBox(-12.0F, -42.0F, -7.0F, 3.0F, 6.0F, 3.0F)
				.texOffs(46, 98)
				.addBox(-13.5F, -38.0F, -9.0F, 3.0F, 3.0F, 3.0F)
				.texOffs(58, 95)
				.addBox(-15.0F, -36.0F, -14.0F, 3.0F, 3.0F, 6.0F)
				.texOffs(76, 95)
				.addBox(-16.0F, -40.0F, -16.0F, 3.0F, 6.0F, 3.0F)
				.texOffs(88, 97)
				.addBox(-17.0F, -42.0F, -14.0F, 3.0F, 3.0F, 4.0F),
			PartPose.offset(0.0F, 36.0F, 11.0F));

		PartDefinition neck = partdefinition.addOrReplaceChild("neck", CubeListBuilder.create(),
			PartPose.offset(0.0F, -8.0F, -11.0F));

		neck.addOrReplaceChild("neck_r1", CubeListBuilder.create()
				.texOffs(66, 37)
				.addBox(-9.5F, -14.0F, -1.0F, 11.0F, 14.0F, 12.0F, new CubeDeformation(-0.001F)),
			PartPose.offsetAndRotation(4.0F, 8.0F, -3.0F, 0.2618F, 0.0F, 0.0F));

		partdefinition.addOrReplaceChild("front_torso", CubeListBuilder.create()
				.texOffs(0, 0)
				.addBox(-9.0F, -32.0F, -15.0F, 18.0F, 15.0F, 15.0F),
			PartPose.offset(0.0F, 24.0F, 0.0F));

		partdefinition.addOrReplaceChild("back_torso", CubeListBuilder.create()
				.texOffs(0, 30)
				.addBox(-9.0F, -32.0F, 0.0F, 18.0F, 15.0F, 15.0F),
			PartPose.offset(0.0F, 24.0F, 0.0F));

		partdefinition.addOrReplaceChild("left_front_leg", CubeListBuilder.create()
				.texOffs(90, 20)
				.addBox(-3.5F, -5.5F, -3.5F, 7.0F, 10.0F, 7.0F)
				.texOffs(66, 18)
				.addBox(-3.0F, 4.0F, -3.0F, 6.0F, 13.0F, 6.0F),
			PartPose.offset(6.0F, 7.0F, -10.5F));

		partdefinition.addOrReplaceChild("right_front_leg", CubeListBuilder.create().mirror()
				.texOffs(90, 20)
				.addBox(-3.5F, -5.5F, -3.5F, 7.0F, 10.0F, 7.0F)
				.texOffs(66, 18)
				.addBox(-3.0F, 4.0F, -3.0F, 6.0F, 13.0F, 6.0F),
			PartPose.offset(-6.0F, 7.0F, -10.5F));

		partdefinition.addOrReplaceChild("left_back_leg", CubeListBuilder.create()
				.texOffs(90, 0)
				.addBox(-3.5F, -4.5F, -6.0F, 7.0F, 10.0F, 10.0F)
				.texOffs(66, 0)
				.addBox(-3.0F, 5.0F, -3.0F, 6.0F, 12.0F, 6.0F),
			PartPose.offset(6.0F, 7.0F, 9.0F));

		partdefinition.addOrReplaceChild("right_back_leg", CubeListBuilder.create().mirror()
				.texOffs(90, 0)
				.addBox(-3.5F, -4.5F, -6.0F, 7.0F, 10.0F, 10.0F)
				.texOffs(66, 0)
				.addBox(-3.0F, 5.0F, -3.0F, 6.0F, 12.0F, 6.0F),
			PartPose.offset(-6.0F, 7.0F, 9.0F));

		CubeListBuilder wool = CubeListBuilder.create()
			.texOffs(0, 104)
			.addBox(-9F, -7.5F, 0.0F, 18.0F, 15.0F, 2.0F);

		for (int i = 0; i < 16; i++) {
			partdefinition.addOrReplaceChild(getSegmentName(i), wool, PartPose.offset(0.0F, -0.5F, 0.0F));
		}

		return LayerDefinition.create(meshdefinition, 128, 128);
	}

	private static String getSegmentName(int num) {
		return "segment" + num;
	}

	@Override
	public void renderToBuffer(PoseStack stack, VertexConsumer builder, int light, int overlay, int color) {
		super.renderToBuffer(stack, builder, light, overlay, color);

		for (int i = 0; i < 16; i++) {
			final int dyeRgb = DyeColor.byId(i).getTextureDiffuseColor();
			segments[i].render(stack, builder, light, overlay, dyeRgb);
		}
	}

	@Override
	public void setupAnim(QuestingRamRenderState state) {
		super.setupAnim(state);

		// how many colors should we display?
		int count = state.countColorsSet();

		this.head.z = -count - 11;
		this.neck.z = -count - 11;
		this.frontTorso.z = -count;
		this.backTorso.z = count;
		this.leftBackLeg.z = 9 + count;
		this.rightBackLeg.z = 9 + count;
		this.leftFrontLeg.z = -11 - count;
		this.rightFrontLeg.z = -11 - count;

		// set up the colors displayed in color order
		int segmentOffset = 0;
		for (int color : this.colorOrder) {
			if (state.isColorPresent(DyeColor.byId(color))) {
				this.segments[color].visible = true;
				this.segments[color].z = segmentOffset - count;

				segmentOffset += 2;
			} else {
				this.segments[color].visible = false;
			}
		}
		this.head.xRot = state.xRot * Mth.DEG_TO_RAD;
		this.head.yRot = state.yRot * Mth.DEG_TO_RAD;

		this.neck.yRot = this.head.yRot;

		this.leftFrontLeg.xRot = Mth.cos(state.walkAnimationPos * 0.6662F) * 1.4F * state.walkAnimationSpeed * 0.5F;
		this.rightFrontLeg.xRot = Mth.cos(state.walkAnimationPos * 0.6662F + Mth.PI) * 1.4F * state.walkAnimationSpeed * 0.5F;
		this.leftBackLeg.xRot = Mth.cos(state.walkAnimationPos * 0.6662F + Mth.PI) * 1.4F * state.walkAnimationSpeed * 0.5F;
		this.rightBackLeg.xRot = Mth.cos(state.walkAnimationPos * 0.6662F) * 1.4F * state.walkAnimationSpeed * 0.5F;
	}

	@Override
	public void renderTrophy(PoseStack stack, SubmitNodeCollector collector, int light, ItemDisplayContext context) {
		stack.scale(0.67F, 0.67F, 0.67F);
		stack.translate(0.0F, 0.5F, context != ItemDisplayContext.NONE ? 0.5F : 0.67F);

		collector.submitModelPart(this.head, stack, RenderTypes.entityCutout(QuestRamRenderer.TEXTURE), light, OverlayTexture.NO_OVERLAY, null);
		stack.pushPose();
		stack.scale(1.025F, 1.025F, 1.025F);
		collector.submitModelPart(this.head, stack, RenderTypes.entityTranslucent(QuestRamRenderer.TEXTURE), LightCoordsUtil.FULL_BRIGHT, OverlayTexture.NO_OVERLAY, null);
		stack.popPose();
	}
}
