package twilightforest.client;

import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.ItemBlockRenderTypes;
import twilightforest.block.TFBlocks;

public class RenderLayerRegistration {
	public static void init() {
		RenderType cutoutMipped = RenderType.cutoutMipped();
		RenderType cutout = RenderType.cutout();
		RenderType translucent = RenderType.translucent();
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_OAK_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.RAINBOW_OAK_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CANOPY_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MANGROVE_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TRANSFORMATION_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MINING_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_DOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TRANSFORMATION_DOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_DOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_OAK_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_SPRUCE_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_BIRCH_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_JUNGLE_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_ACACIA_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_DARK_OAK_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_CRIMSON_STEM_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_WARPED_STEM_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_TWILIGHT_OAK_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_CANOPY_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_MANGROVE_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_DARK_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_TIME_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_TRANSFORMATION_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_MINING_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_SORTING_LOG_HORIZONTAL.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_TWILIGHT_OAK_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_CANOPY_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_MANGROVE_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_DARK_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_TIME_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_TRANSFORMATION_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_MINING_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_SORTING_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_OAK_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_SPRUCE_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_BIRCH_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_JUNGLE_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_ACACIA_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_DARK_OAK_LOG_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_CRIMSON_STEM_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_WARPED_STEM_CLIMBABLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_TRAPDOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_TRAPDOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_PORTAL.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.AURORALIZED_GLASS.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.THORN_ROSE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIERY_BLOCK.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.THORN_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BEANSTALK_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GIANT_LEAVES.get(), cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.EXPERIMENT_115.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.WISPY_CLOUD.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UBEROUS_SOIL.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TROLLVIDR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UNRIPE_TROLLBER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TROLLBER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HUGE_LILY_PAD.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HUGE_WATER_LILY.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.YELLOW_CASTLE_RUNE_BRICK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VIOLET_CASTLE_RUNE_BRICK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.PINK_CASTLE_RUNE_BRICK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BLUE_CASTLE_RUNE_BRICK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.YELLOW_CASTLE_DOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VIOLET_CASTLE_DOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.PINK_CASTLE_DOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BLUE_CASTLE_DOOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GREEN_THORNS.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BROWN_THORNS.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BURNT_THORNS.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_PORTAL_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.HEDGE_MAZE_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.HOLLOW_HILL_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.QUEST_GROVE_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.MUSHROOM_TOWER_MINIATURE_STRUCTURE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.NAGA_COURTYARD_MINIATURE_STRUCTURE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.LICH_TOWER_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.MINOTAUR_LABYRINTH_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.HYDRA_LAIR_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.GOBLIN_STRONGHOLD_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.DARK_TOWER_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.YETI_CAVE_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.AURORA_PALACE_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.TROLL_CAVE_COTTAGE_MINIATURE_STRUCTURE.get(), cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.FINAL_CASTLE_MINIATURE_STRUCTURE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TROPHY_PEDESTAL.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWISTED_STONE_PILLAR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CANDELABRA.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIERY_BLOCK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIREFLY_JAR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIREFLY_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CICADA_JAR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MOSS_PATCH.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MAYAPPLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CLOVER_PATCH.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIDDLEHEAD.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MUSHGLOOM.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TORCHBERRY_PLANT.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ROOT_STRAND.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FALLEN_LEAVES.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UNCRAFTING_TABLE.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ENCASED_SMOKER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ENCASED_FIRE_JET.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_OAK_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.RAINBOW_OAK_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CANOPY_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MANGROVE_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.DARKWOOD_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_OAK_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TRANSFORMATION_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MINING_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BUILT_BLOCK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ANTIBUILT_BLOCK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.REACTOR_DEBRIS.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.PINK_FORCE_FIELD.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BLUE_FORCE_FIELD.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GREEN_FORCE_FIELD.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VIOLET_FORCE_FIELD.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ORANGE_FORCE_FIELD.get(), translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.NAGA_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.LICH_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HYDRA_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UR_GHAST_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.KNIGHT_PHANTOM_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SNOW_QUEEN_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MINOSHROOM_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ALPHA_YETI_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FINAL_BOSS_BOSS_SPAWNER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.REAPPEARING_BLOCK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.LOCKED_VANISHING_BLOCK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VANISHING_BLOCK.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CARMINITE_BUILDER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ANTIBUILDER.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CARMINITE_REACTOR.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GHAST_TRAP.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_TWILIGHT_OAK_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_CANOPY_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MANGROVE_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_DARKWOOD_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_HOLLOW_OAK_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_RAINBOW_OAK_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_TIME_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_TRANSFORMATION_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MINING_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_SORTING_SAPLING.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MAYAPPLE.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_FIDDLEHEAD.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MUSHGLOOM.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_THORN.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_GREEN_THORN.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_DEAD_THORN.get(), cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.RED_THREAD.get(), cutout);
	}
}
