package twilightforest.init;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.levelgen.structure.pieces.StructurePieceType;
import twilightforest.TwilightForestMod;
import twilightforest.world.components.structures.*;
import twilightforest.world.components.structures.courtyard.*;
import twilightforest.world.components.structures.darktower.*;
import twilightforest.world.components.structures.fallentrunk.FallenTrunkPiece;
import twilightforest.world.components.structures.finalcastle.*;
import twilightforest.world.components.structures.hollowtree.*;
import twilightforest.world.components.structures.icetower.*;
import twilightforest.world.components.structures.lichtower.*;
import twilightforest.world.components.structures.lichtowerrevamp.*;
import twilightforest.world.components.structures.minotaurmaze.*;
import twilightforest.world.components.structures.mushroomtower.*;
import twilightforest.world.components.structures.stronghold.*;
import twilightforest.world.components.structures.trollcave.*;

import java.util.Locale;

public final class TFStructurePieceTypes {
    public static final TFRegistryObject<StructurePieceType> TFClCa = piece("TFClCa", CloudCastleComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFCloud = piece("TFCloud", CloudComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFClTr = piece("TFClTr", CloudTreeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFQuestGrove = piece("TFQuest1", QuestGrove::new);
    public static final TFRegistryObject<StructurePieceType> TFNCMn = piece("TFNCMn", CourtyardMain::new);
    public static final TFRegistryObject<StructurePieceType> TFNCCp = piece("TFNCCp", NagaCourtyardHedgeCapComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFNCCpP = piece("TFNCCpP", NagaCourtyardHedgeCapPillarComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFNCCr = piece("TFNCCr", NagaCourtyardHedgeCornerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFNCLn = piece("TFNCLn", NagaCourtyardHedgeLineComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFNCT = piece("TFNCT", NagaCourtyardHedgeTJunctionComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFNCIs = piece("TFNCIs", NagaCourtyardHedgeIntersectionComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFNCPd = piece("TFNCPd", NagaCourtyardHedgePadderComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFNCTe = piece("TFNCTe", CourtyardTerrace::new);
    public static final TFRegistryObject<StructurePieceType> TFNCHe = piece("TFNCHe", CourtyardTerraceHedge::new);
    public static final TFRegistryObject<StructurePieceType> TFNCTr = piece("TFNCTr", CourtyardTerraceBrazier::new);
    public static final TFRegistryObject<StructurePieceType> TFNCDu = piece("TFNCDu", CourtyardTerraceDuct::new);
    public static final TFRegistryObject<StructurePieceType> TFNCSt = piece("TFNCSt", CourtyardTerraceStatue::new);
    public static final TFRegistryObject<StructurePieceType> TFNCPa = piece("TFNCPa", CourtyardPathPiece::new);
    public static final TFRegistryObject<StructurePieceType> TFNCWl = piece("TFNCWl", CourtyardWall::new);
    public static final TFRegistryObject<StructurePieceType> TFNCWP = piece("TFNCWP", CourtyardWallPadder::new);
    public static final TFRegistryObject<StructurePieceType> TFNCWC = piece("TFNCWC", CourtyardWallCornerOuter::new);
    public static final TFRegistryObject<StructurePieceType> TFNCWA = piece("TFNCWA", CourtyardWallCornerInner::new);
    public static final TFRegistryObject<StructurePieceType> TFDTBal = piece("TFDTBal", DarkTowerBalconyComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTBB = piece("TFDTBB", DarkTowerBossBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTBea = piece("TFDTBea", DarkTowerBeardComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTBri = piece("TFDTBri", DarkTowerBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTBT = piece("TFDTBT", DarkTowerBossTrapComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTEB = piece("TFDTEB", DarkTowerEntranceBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTEnt = piece("TFDTEnt", DarkTowerEntranceComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTMai = piece("TFDTMai", DarkTowerMainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTMB = piece("TFDTMB", DarkTowerMainBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTRA = piece("TFDTRA", DarkTowerRoofAntennaComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTRC = piece("TFDTRC", DarkTowerRoofCactusComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTRFP = piece("TFDTRFP", DarkTowerRoofFourPostComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTRooS = piece("TFDTRooS", DarkTowerRoofComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTRR = piece("TFDTRR", DarkTowerRoofRingsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFDTWin = piece("TFDTWin", DarkTowerWingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFallenTrunk = piece("TFFallenTrunk", FallenTrunkPiece::new);
    public static final TFRegistryObject<StructurePieceType> TFHedge = piece("TFHedge", HedgeMazeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFHill = piece("TFHill", HollowHillComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFHTLB = piece("TFHTLB", HollowTreeLargeBranch::new);
    public static final TFRegistryObject<StructurePieceType> TFHTLD = piece("TFHTLD", HollowTreeLeafDungeon::new);
    public static final TFRegistryObject<StructurePieceType> TFHTMB = piece("TFHTMB", HollowTreeMedBranch::new);
    public static final TFRegistryObject<StructurePieceType> TFHTRo = piece("TFHTRo", HollowTreeRoot::new);
    public static final TFRegistryObject<StructurePieceType> TFHTSB = piece("TFHTSB", HollowTreeSmallBranch::new);
    public static final TFRegistryObject<StructurePieceType> TFHTTr = piece("TFHTTr", HollowTreeTrunk::new);
    public static final TFRegistryObject<StructurePieceType> TFHydra = piece("TFHydra", HydraLairComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITBea = piece("TFITBea", IceTowerBeardComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITBoss = piece("TFITBoss", IceTowerBossWingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITBri = piece("TFITBri", IceTowerBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITEnt = piece("TFITEnt", IceTowerEntranceComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITMai = piece("TFITMai", IceTowerMainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITRoof = piece("TFITRoof", IceTowerRoofComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITSt = piece("TFITSt", IceTowerStairsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFITWin = piece("TFITWin", IceTowerWingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTBA = piece("TFLTBA", TowerBeardAttachedComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTBea = piece("TFLTBea", TowerBeardComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTBri = piece("TFLTBri", TowerBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTMai = piece("TFLTMai", TowerMainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTOut = piece("TFLTOut", TowerOutbuildingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRAS = piece("TFLTRAS", TowerRoofAttachedSlabComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRF = piece("TFLTRF", TowerRoofFenceComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRGF = piece("TFLTRGF", TowerRoofGableForwardsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRoo = piece("TFLTRoo", TowerRoofComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRP = piece("TFLTRP", TowerRoofPointyComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRPO = piece("TFLTRPO", TowerRoofPointyOverhangComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRS = piece("TFLTRS", TowerRoofSlabComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRSF = piece("TFLTRSF", TowerRoofSlabForwardsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRSt = piece("TFLTRSt", TowerRoofStairsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTRStO = piece("TFLTRStO", TowerRoofStairsOverhangComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFLTWin = piece("TFLTWin", TowerWingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFJigsawTemplate = piece("TFJigsawTemplate", TwilightJigsawPiece::defaultDeserialize);
    public static final TFRegistryObject<StructurePieceType> LICH_TOWER_FOYER = piece("TFLTTFoy", LichTowerFoyer::new);
    public static final TFRegistryObject<StructurePieceType> LICH_TOWER_BASE = piece("TFLTCTBase", LichTowerBase::new);
    public static final TFRegistryObject<StructurePieceType> LICH_TOWER_BASE_TRIM = piece("TFLTCTTrim", LichTowerBaseTrim::new);
    public static final TFRegistryObject<StructurePieceType> LICH_TOWER_SEGMENT = piece("TFLTCTSeg", LichTowerSegment::new);
    public static final TFRegistryObject<StructurePieceType> LICH_SPAWNER_BRIDGE = piece("TFLTMobBridge", LichTowerSpawnerBridge::new);
    public static final TFRegistryObject<StructurePieceType> LICH_WING_BRIDGE = piece("TFLTBridge", LichTowerWingBridge::new);
    public static final TFRegistryObject<StructurePieceType> LICH_WING_ROOF = piece("TFLTTRoof", LichTowerWingRoof::new);
    public static final TFRegistryObject<StructurePieceType> LICH_WING_BEARD = piece("TFLTTBeard", LichTowerWingBeard::new);
    public static final TFRegistryObject<StructurePieceType> LICH_WING_ROOM = piece("TFLTTRoom", LichTowerWingRoom::new);
    public static final TFRegistryObject<StructurePieceType> LICH_TOWER_DECOR = piece("TFLTTDecor", LichTowerRoomDecor::new);
    public static final TFRegistryObject<StructurePieceType> LICH_MAGIC_GALLERY = piece("TFLTTGallery", LichTowerMagicGallery::new);
    public static final TFRegistryObject<StructurePieceType> LICH_FOYER_DECORATION = piece("TFLTTFoyD", LichTowerFoyerDecor::new);
    public static final TFRegistryObject<StructurePieceType> LICH_BOSS_ROOM = piece("TFLTTBoss", LichBossRoom::new);
    public static final TFRegistryObject<StructurePieceType> LICH_BOSS_ROOF = piece("TFLTTBossRoof", LichBossRoof::new);
    public static final TFRegistryObject<StructurePieceType> LICH_PERIMETER_FENCE = piece("TFLTFence", LichPerimeterFence::new);
    public static final TFRegistryObject<StructurePieceType> LICH_YARD_PATH = piece("TFLTPath", LichYardBox::new);
    public static final TFRegistryObject<StructurePieceType> LICH_YARD_GRAVE = piece("TFLTGrave", LichYardGrave::new);
    public static final TFRegistryObject<StructurePieceType> LICH_YARD_LIGHTS = piece("TFLTLight", LichYardLights::new);
    public static final TFRegistryObject<StructurePieceType> TFMMaze = piece("TFMMaze", MinotaurMazeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMC = piece("TFMMC", MazeCorridorComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMCIF = piece("TFMMCIF", MazeCorridorIronFenceComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMCR = piece("TFMMCR", MazeCorridorRootsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMCS = piece("TFMMCS", MazeCorridorShroomsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDE = piece("TFMMDE", MazeDeadEndComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDEC = piece("TFMMDEC", MazeDeadEndChestComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDEF = piece("TFMMDEF", MazeDeadEndFountainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDEFL = piece("TFMMDEFL", MazeDeadEndFountainLavaComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDEP = piece("TFMMDEP", MazeDeadEndPaintingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDER = piece("TFMMDER", MazeDeadEndRootsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDES = piece("TFMMDES", MazeDeadEndShroomsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDET = piece("TFMMDET", MazeDeadEndTorchesComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDETC = piece("TFMMDETC", MazeDeadEndTripwireChestComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMDETrC = piece("TFMMDETrC", MazeDeadEndTrappedChestComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMES = piece("TFMMES", MazeEntranceShaftComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMMound = piece("TFMMMound", MazeMoundComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMMR = piece("TFMMMR", MazeMushRoomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMR = piece("TFMMR", MazeRoomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMRB = piece("TFMMRB", MazeRoomBossComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMRC = piece("TFMMRC", MazeRoomCollapseComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMRE = piece("TFMMRE", MazeRoomExitComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMRF = piece("TFMMRF", MazeRoomFountainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMRSC = piece("TFMMRSC", MazeRoomSpawnerChestsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMRuins = piece("TFMMRuins", MazeRuinsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMRV = piece("TFMMRV", MazeRoomVaultComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMMUE = piece("TFMMUE", MazeUpperEntranceComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMTBri = piece("TFMTBri", MushroomTowerBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMTMai = piece("TFMTMai", MushroomTowerMainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMTMB = piece("TFMTMB", MushroomTowerMainBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMTRoofMush = piece("TFMTRoofMush", TowerRoofMushroomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFMTWin = piece("TFMTWin", MushroomTowerWingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSAC = piece("TFSAC", StrongholdAccessChamberComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSAt = piece("TFSAt", StrongholdAtriumComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSBalR = piece("TFSBalR", StrongholdBalconyRoomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSBR = piece("TFSBR", StrongholdBossRoomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSCr = piece("TFSCr", StrongholdCrossingComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSDE = piece("TFSDE", StrongholdDeadEndComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSEnter = piece("TFSEnter", StrongholdEntranceComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSFo = piece("TFSFo", StrongholdFoundryComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSLT = piece("TFSLT", StrongholdLeftTurnComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSRT = piece("TFSRT", StrongholdRightTurnComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSSH = piece("TFSSH", StrongholdSmallHallwayComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSShield = piece("TFSShield", StrongholdShieldStructure::new);
    public static final TFRegistryObject<StructurePieceType> TFSSS = piece("TFSSS", StrongholdSmallStairsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSTC = piece("TFSTC", StrongholdTreasureCorridorComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSTR = piece("TFSTR", StrongholdTrainingRoomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSUA = piece("TFSUA", StrongholdUpperAscenderComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSUCo = piece("TFSUCo", StrongholdUpperCorridorComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSULT = piece("TFSULT", StrongholdUpperLeftTurnComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSURT = piece("TFSURT", StrongholdUpperRightTurnComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFSUTI = piece("TFSUTI", StrongholdUpperTIntersectionComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFTCCon = piece("TFTCCon", TrollCaveConnectComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFTCGard = piece("TFTCGard", TrollCaveGardenComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFTCloud = piece("TFTCloud", TrollCloudComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFTCMai = piece("TFTCMai", TrollCaveMainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFTCVa = piece("TFTCVa", TrollVaultComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCMain = piece("TFFCMain", FinalCastleMainComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCStTo = piece("TFFCStTo", FinalCastleStairTowerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCLaTo = piece("TFFCLaTo", FinalCastleLargeTowerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCMur = piece("TFFCMur", FinalCastleMuralComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCToF48 = piece("TFFCToF48", FinalCastleFoundation48Component::new);
    public static final TFRegistryObject<StructurePieceType> TFFCRo48Cr = piece("TFFCRo48Cr", FinalCastleRoof48CrenellatedComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCBoGaz = piece("TFFCBoGaz", FinalCastleBossGazeboComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCSiTo = piece("TFFCSiTo", FinalCastleMazeTower13Component::new);
    public static final TFRegistryObject<StructurePieceType> TFFCDunSt = piece("TFFCDunSt", FinalCastleDungeonStepsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCDunEn = piece("TFFCDunEn", FinalCastleDungeonEntranceComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCDunR31 = piece("TFFCDunR31", FinalCastleDungeonRoom31Component::new);
    public static final TFRegistryObject<StructurePieceType> TFFCDunEx = piece("TFFCDunEx", FinalCastleDungeonExitComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCDunBoR = piece("TFFCDunBoR", FinalCastleDungeonForgeRoomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCRo9Cr = piece("TFFCRo9Cr", FinalCastleRoof9CrenellatedComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCRo13Cr = piece("TFFCRo13Cr", FinalCastleRoof13CrenellatedComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCRo13Con = piece("TFFCRo13Con", FinalCastleRoof13ConicalComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCRo13Pk = piece("TFFCRo13Pk", FinalCastleRoof13PeakedComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCEnTo = piece("TFFCEnTo", FinalCastleEntranceTowerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCEnSiTo = piece("TFFCEnSiTo", FinalCastleEntranceSideTowerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCEnBoTo = piece("TFFCEnBoTo", FinalCastleEntranceBottomTowerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCEnSt = piece("TFFCEnSt", FinalCastleEntranceStairsComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCBelTo = piece("TFFCBelTo", FinalCastleBellTower21Component::new);
    public static final TFRegistryObject<StructurePieceType> TFFCBri = piece("TFFCBri", FinalCastleBridgeComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCToF13 = piece("TFFCToF13", FinalCastleFoundation13Component::new);
    public static final TFRegistryObject<StructurePieceType> TFFCBeF21 = piece("TFFCBeF21", FinalCastleBellFoundation21Component::new);
    public static final TFRegistryObject<StructurePieceType> TFFCFTh21 = piece("TFFCFTh21", FinalCastleFoundation13ComponentThorns::new);
    public static final TFRegistryObject<StructurePieceType> TFFCDamT = piece("TFFCDamT", FinalCastleDamagedTowerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFFCWrT = piece("TFFCWrT", FinalCastleWreckedTowerComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFTreaR = piece("TFTreaR", StrongholdTreasureRoomComponent::new);
    public static final TFRegistryObject<StructurePieceType> TFUtilityPiece = piece("TFUtilityPiece", UtilityPiece::new);
    public static final TFRegistryObject<StructurePieceType> TFYeti = piece("TFYeti", YetiCaveComponent::new);

    private TFStructurePieceTypes() {
    }

    public static void bootstrap() {
    }

    private static TFRegistryObject<StructurePieceType> piece(String name, StructurePieceType type) {
        String path = name.toLowerCase(Locale.ROOT);
        ResourceKey<StructurePieceType> key = ResourceKey.create(BuiltInRegistries.STRUCTURE_PIECE.key(), TwilightForestMod.prefix(path));
        return new TFRegistryObject<>(Registry.register(BuiltInRegistries.STRUCTURE_PIECE, key.location(), type), key);
    }
}
